use strict;
use warnings;
package Net::Continental;

# XXX: In Net::Domain::TLD but not supported by countries.nerd.dk
my @data = qw(
  in_nerd continent code description
);

my @zones = (
  [ 0 => F => ac => q{Ascension Island} ],
  [ 0 => E => ax => q(Aland Islands) ],
  [ 0 => N => bl => q(Saint Barthelemy) ],
  [ 0 => F => cd => q{Congo, Democratic Republic of the} ],
  [ 0 => E => eu => q{European Union} ],
  [ 0 => E => im => q{Isle of Man} ],
  [ 0 => E => je => q{Jersey} ],
  [ 0 => E => me => q(Montenegro) ],
  [ 0 => N => mf => q{Saint Martin (French part)} ],
  [ 0 => E => rs => q(Serbia) ],
  [ 0 => A => tl => q{Timor-Leste} ],

  [ 1 => A => ae => q{United Arab Emirates} ],
  [ 1 => A => af => q{Afghanistan} ],
  [ 1 => A => az => q{Azerbaijan} ],
  [ 1 => A => bd => q{Bangladesh} ],
  [ 1 => A => bh => q{Bahrain} ],
  [ 1 => A => bt => q{Bhutan} ],
  [ 1 => A => cn => q{China} ],
  [ 1 => A => ge => q{Georgia}, ], # classification of Georgia in Europe or Asia is touchy
  [ 1 => A => hk => q{Hong Kong} ],
  [ 1 => A => il => q{Israel} ],
  [ 1 => A => in => q{India} ],
  [ 1 => A => iq => q{Iraq} ],
  [ 1 => A => ir => q{Iran (Islamic Republic of)} ],
  [ 1 => A => jo => q{Jordan} ],
  [ 1 => A => jp => q{Japan} ],
  [ 1 => A => kg => q{Kyrgyzstan} ],
  [ 1 => A => kh => q{Cambodia} ],
  [ 1 => A => kp => q{Korea, Democratic People's Republic} ],
  [ 1 => A => kr => q{Korea, Republic of} ],
  [ 1 => A => kw => q{Kuwait} ],
  [ 1 => A => kz => q{Kazakhstan} ],
  [ 1 => A => la => q{Lao People's Democratic Republic} ],
  [ 1 => A => lb => q{Lebanon} ],
  [ 1 => A => lk => q{Sri Lanka} ],
  [ 1 => A => mm => q{Myanmar} ],
  [ 1 => A => mn => q{Mongolia} ],
  [ 1 => A => mo => q{Macau} ],
  [ 1 => A => mv => q{Maldives} ],
  [ 1 => A => my => q{Malaysia} ],
  [ 1 => A => np => q{Nepal} ],
  [ 1 => A => om => q{Oman} ],
  [ 1 => A => ph => q{Philippines} ],
  [ 1 => A => pk => q{Pakistan} ],
  [ 1 => A => ps => q{Palestinian Territories} ],
  [ 1 => A => qa => q{Qatar} ],
  [ 1 => A => ru => q{Russian Federation} ],
  [ 1 => A => sa => q{Saudi Arabia} ],
  [ 1 => A => sg => q{Singapore} ],
  [ 1 => A => su => q{Soviet Union} ],
  [ 1 => A => sy => q{Syrian Arab Republic} ],
  [ 1 => A => th => q{Thailand} ],
  [ 1 => A => tj => q{Tajikistan} ],
  [ 1 => A => tm => q{Turkmenistan} ],
  [ 1 => A => tp => q{East Timor} ],
  [ 1 => A => tr => q{Turkey} ],
  [ 1 => A => tw => q{Taiwan} ],
  [ 1 => A => uz => q{Uzbekistan} ],
  [ 1 => A => vn => q{Vietnam} ],
  [ 1 => A => ye => q{Yemen} ],
  [ 1 => E => ad => q{Andorra} ],
  [ 1 => E => al => q{Albania} ],
  [ 1 => E => am => q{Armenia} ],
  [ 1 => E => at => q{Austria} ],
  [ 1 => E => ba => q{Bosnia and Herzegovina} ],
  [ 1 => E => be => q{Belgium} ],
  [ 1 => E => bg => q{Bulgaria} ],
  [ 1 => E => by => q{Belarus} ],
  [ 1 => E => ch => q{Switzerland} ],
  [ 1 => E => cy => q{Cyprus} ],
  [ 1 => E => cz => q{Czech Republic} ],
  [ 1 => E => de => q{Germany} ],
  [ 1 => E => dk => q{Denmark} ],
  [ 1 => E => ee => q{Estonia} ],
  [ 1 => E => es => q{Spain} ],
  [ 1 => E => fi => q{Finland} ],
  [ 1 => E => fo => q{Faroe Islands} ],
  [ 1 => E => fr => q{France} ],
  [ 1 => E => fx => q{France, Metropolitan} ],
  [ 1 => E => gb => q{United Kingdom} ],
  [ 1 => E => gg => q{Guernsey} ],
  [ 1 => E => gi => q{Gibraltar} ],
  [ 1 => E => gr => q{Greece} ],
  [ 1 => E => hr => q{Croatia/Hrvatska} ],
  [ 1 => E => hu => q{Hungary} ],
  [ 1 => E => ie => q{Ireland} ],
  [ 1 => E => is => q{Iceland} ],
  [ 1 => E => it => q{Italy} ],
  [ 1 => E => li => q{Liechtenstein} ],
  [ 1 => E => lt => q{Lithuania} ],
  [ 1 => E => lu => q{Luxembourg} ],
  [ 1 => E => lv => q{Latvia} ],
  [ 1 => E => mc => q{Monaco} ],
  [ 1 => E => md => q{Moldova, Republic of} ],
  [ 1 => E => mk => q{Macedonia, Former Yugoslav Republic} ],
  [ 1 => E => mt => q{Malta} ],
  [ 1 => E => nl => q{Netherlands} ],
  [ 1 => E => no => q{Norway} ],
  [ 1 => E => pl => q{Poland} ],
  [ 1 => E => pt => q{Portugal} ],
  [ 1 => E => ro => q{Romania} ],
  [ 1 => E => se => q{Sweden} ],
  [ 1 => E => si => q{Slovenia} ],
  [ 1 => E => sj => q{Svalbard and Jan Mayen Islands} ],
  [ 1 => E => sk => q{Slovak Republic} ],
  [ 1 => E => sm => q{San Marino} ],
  [ 1 => E => ua => q{Ukraine} ],
  [ 1 => E => uk => q{United Kingdom} ],
  [ 1 => E => va => q{Holy See (City Vatican State)} ],
  [ 1 => E => yu => q{Yugoslavia} ],
  [ 1 => F => ao => q{Angola} ],
  [ 1 => F => bf => q{Burkina Faso} ],
  [ 1 => F => bi => q{Burundi} ],
  [ 1 => F => bj => q{Benin} ],
  [ 1 => F => bw => q{Botswana} ],
  [ 1 => F => cf => q{Central African Republic} ],
  [ 1 => F => cg => q{Congo, Republic of} ],
  [ 1 => F => ci => q{Cote d'Ivoire} ],
  [ 1 => F => cm => q{Cameroon} ],
  [ 1 => F => cv => q{Cap Verde} ],
  [ 1 => F => dj => q{Djibouti} ],
  [ 1 => F => dz => q{Algeria} ],
  [ 1 => F => eg => q{Egypt} ],
  [ 1 => F => eh => q{Western Sahara} ],
  [ 1 => F => er => q{Eritrea} ],
  [ 1 => F => et => q{Ethiopia} ],
  [ 1 => F => ga => q{Gabon} ],
  [ 1 => F => gf => q{French Guiana} ],
  [ 1 => F => gh => q{Ghana} ],
  [ 1 => F => gm => q{Gambia} ],
  [ 1 => F => gn => q{Guinea} ],
  [ 1 => F => gq => q{Equatorial Guinea} ],
  [ 1 => F => gw => q{Guinea-Bissau} ],
  [ 1 => F => gy => q{Guyana} ],
  [ 1 => F => ke => q{Kenya} ],
  [ 1 => F => km => q{Comoros} ],
  [ 1 => F => lr => q{Liberia} ],
  [ 1 => F => ls => q{Lesotho} ],
  [ 1 => F => ly => q{Libyan Arab Jamahiriya} ],
  [ 1 => F => ma => q{Morocco} ],
  [ 1 => F => mg => q{Madagascar} ],
  [ 1 => F => ml => q{Mali} ],
  [ 1 => F => mr => q{Mauritania} ],
  [ 1 => F => mu => q{Mauritius} ],
  [ 1 => F => mw => q{Malawi} ],
  [ 1 => F => mz => q{Mozambique} ],
  [ 1 => F => na => q{Namibia} ],
  [ 1 => F => ne => q{Niger} ],
  [ 1 => F => ng => q{Nigeria} ],
  [ 1 => F => re => q{Reunion Island} ],
  [ 1 => F => rw => q{Rwanda} ],
  [ 1 => F => sc => q{Seychelles} ],
  [ 1 => F => sd => q{Sudan} ],
  [ 1 => F => sh => q{St. Helena} ],
  [ 1 => F => sl => q{Sierra Leone} ],
  [ 1 => F => sn => q{Senegal} ],
  [ 1 => F => so => q{Somalia} ],
  [ 1 => F => st => q{Sao Tome and Principe} ],
  [ 1 => F => sz => q{Swaziland} ],
  [ 1 => F => td => q{Chad} ],
  [ 1 => F => tg => q{Togo} ],
  [ 1 => F => tn => q{Tunisia} ],
  [ 1 => F => to => q{Tonga} ],
  [ 1 => F => tz => q{Tanzania} ],
  [ 1 => F => ug => q{Uganda} ],
  [ 1 => F => yt => q{Mayotte} ],
  [ 1 => F => za => q{South Africa} ],
  [ 1 => F => zm => q{Zambia} ],
  [ 1 => F => zr => q{Zaire} ],
  [ 1 => F => zw => q{Zimbabwe} ],
  [ 1 => N => ag => q{Antigua and Barbuda} ],
  [ 1 => N => ai => q{Anguilla} ],
  [ 1 => N => an => q{Netherlands Antilles} ],
  [ 1 => N => aw => q{Aruba} ],
  [ 1 => N => bb => q{Barbados} ],
  [ 1 => N => bm => q{Bermuda} ],
  [ 1 => N => bo => q{Bolivia} ],
  [ 1 => N => bs => q{Bahamas} ],
  [ 1 => N => bz => q{Belize} ],
  [ 1 => N => ca => q{Canada} ],
  [ 1 => N => co => q{Colombia} ],
  [ 1 => N => cr => q{Costa Rica} ],
  [ 1 => N => cu => q{Cuba} ],
  [ 1 => N => do => q{Dominican Republic} ],
  [ 1 => N => ec => q{Ecuador} ],
  [ 1 => N => gl => q{Greenland} ],
  [ 1 => N => gt => q{Guatemala} ],
  [ 1 => N => hn => q{Honduras} ],
  [ 1 => N => ht => q{Haiti} ],
  [ 1 => N => jm => q{Jamaica} ],
  [ 1 => N => kn => q{Saint Kitts and Nevis} ],
  [ 1 => N => lc => q{Saint Lucia} ],
  [ 1 => N => mq => q{Martinique} ],
  [ 1 => N => ms => q{Montserrat} ],
  [ 1 => N => mx => q{Mexico} ],
  [ 1 => N => ni => q{Nicaragua} ],
  [ 1 => N => pa => q{Panama} ],
  [ 1 => N => pm => q{St. Pierre and Miquelon} ],
  [ 1 => N => pr => q{Puerto Rico} ],
  [ 1 => N => sv => q{El Salvador} ],
  [ 1 => N => tc => q{Turks and Caicos Islands} ],
  [ 1 => N => tt => q{Trinidad and Tobago} ],
  [ 1 => N => us => q{United States} ],
  [ 1 => N => vc => q{Saint Vincent and the Grenadines} ],
  [ 1 => N => vg => q{Virgin Islands (British)} ],
  [ 1 => N => vi => q{Virgin Islands (USA)} ],
  [ 1 => O => as => q{American Samoa} ],
  [ 1 => O => au => q{Australia} ],
  [ 1 => O => bn => q{Brunei Darussalam} ],
  [ 1 => O => cc => q{Cocos (Keeling) Islands} ],
  [ 1 => O => ck => q{Cook Islands} ],
  [ 1 => O => cx => q{Christmas Island} ],
  [ 1 => O => dm => q{Dominica} ],
  [ 1 => O => fj => q{Fiji} ],
  [ 1 => O => fm => q{Micronesia, Federated States of} ],
  [ 1 => O => gu => q{Guam} ],
  [ 1 => O => id => q{Indonesia} ],
  [ 1 => O => io => q{British Indian Ocean Territory} ],
  [ 1 => O => ki => q{Kiribati} ],
  [ 1 => O => ky => q{Cayman Islands} ],
  [ 1 => O => mh => q{Marshall Islands} ],
  [ 1 => O => mp => q{Northern Mariana Islands} ],
  [ 1 => O => nc => q{New Caledonia} ],
  [ 1 => O => nf => q{Norfolk Island} ],
  [ 1 => O => nr => q{Nauru} ],
  [ 1 => O => nu => q{Niue} ],
  [ 1 => O => nz => q{New Zealand} ],
  [ 1 => O => pf => q{French Polynesia} ],
  [ 1 => O => pg => q{Papua New Guinea} ],
  [ 1 => O => pn => q{Pitcairn Island} ],
  [ 1 => O => pw => q{Palau} ],
  [ 1 => O => sb => q{Solomon Islands} ],
  [ 1 => O => tk => q{Tokelau} ],
  [ 1 => O => tv => q{Tuvalu} ],
  [ 1 => O => um => q{US Minor Outlying Islands} ],
  [ 1 => O => vu => q{Vanuatu} ],
  [ 1 => O => wf => q{Wallis and Futuna Islands} ],
  [ 1 => O => ws => q{Western Samoa} ],
  [ 1 => Q => aq => q{Antartica} ],
  [ 1 => Q => bv => q{Bouvet Island} ],
  [ 1 => Q => gs => q{South Georgia and the South Sandwich Islands} ],
  [ 1 => Q => hm => q{Heard and McDonald Islands} ],
  [ 1 => Q => tf => q{French Southern Territories} ],
  [ 1 => S => ar => q{Argentina} ],
  [ 1 => S => br => q{Brazil} ],
  [ 1 => S => cl => q{Chile} ],
  [ 1 => S => fk => q{Falkland Islands (Malvina)} ],
  [ 1 => S => gd => q{Grenada} ],
  [ 1 => S => gp => q{Guadeloupe} ],
  [ 1 => S => pe => q{Peru} ],
  [ 1 => S => py => q{Paraguay} ],
  [ 1 => S => sr => q{Suriname} ],
  [ 1 => S => uy => q{Uruguay} ],
  [ 1 => S => ve => q{Venezuela} ],
);

1;
